### ISSUE TITLE
Add: `Partially Directed Graph` 

### ISSUE THREAD

**Issue by Niccolo-Rocchi** [AlessioZanga/causal-hub#96]
### What feature do you propose?

A `mixed graph` (or `partially directed graph`) may graphically represent the Markov equivalence class of a probability distribution. This type of structure is also the output of various contraint (or score) based discovery algorithms.

We need to implement:
- [x] The structure
- [x] Related traits implementations

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlessioZanga** [comment]
Technically speaking, a `MixedGraph` is not the same of a `PartiallyDirectedGraph`. The former contains undirected, directed and also *bidirected* edges, while the latter contains only undirected and directed edges. Indeed, as partially-directed graphs can be seen as a more general graphical representation of directed and undirected graphs, mixed graphs are a generalization of partially-directed graphs. For instance, issue #82 must return a `PartiallyDirectedGraph`, not a `MixedGraph`.

**Comment by Niccolo-Rocchi** [comment]
> 

You're right, but I'd like to generalize and thus create a general `MixedGraph` structure, with a custom number of edge types. For instance, then, a partially directed graph will be a `MixedGraph` with two types of edges. With this concept we could also provide a future implementation and methods for MAGs and PAGs. It may reduce repetition of code and traits.

**Comment by Niccolo-Rocchi** [comment]
> Technically speaking, a `MixedGraph` is not the same of a `PartiallyDirectedGraph`. The former contains undirected, directed and also _bidirected_ edges, while the latter contains only undirected and directed edges. Indeed, as partially-directed graphs can be seen as a more general graphical representation of directed and undirected graphs, mixed graphs are a generalization of partially-directed graphs. For instance, issue #82 must return a `PartiallyDirectedGraph`, not a `MixedGraph`.

gg

**Comment by AlessioZanga** [comment]
What would be the difference between a `MixedGraph` struct and a `MultiGraph` struct in your design?

**Comment by Niccolo-Rocchi** [comment]
> Technically speaking, a `MixedGraph` is not the same of a `PartiallyDirectedGraph`. The former contains undirected, directed and also _bidirected_ edges, while the latter contains only undirected and directed edges. Indeed, as partially-directed graphs can be seen as a more general graphical representation of directed and undirected graphs, mixed graphs are a generalization of partially-directed graphs. For instance, issue #82 must return a `PartiallyDirectedGraph`, not a `MixedGraph`.

**Comment by Niccolo-Rocchi** [comment]
> What would be the difference between a `MixedGraph` struct and a `MultiGraph` struct in your design?

1. `MultipleDenseMatrixGraph` is the vector type I mentioned when talking about generalizing adjacency matrix, in my previous comment.
2. `MixedDenseAdjacencyMatrixGraph` struct is what we called `MixedGraph`. This name is coherent with `DirectedDenseAdjacencyMatrixGraph` and `UndirectedDenseAdjacencyMatrixGraph`, and it leverages `MultipleDenseMatrixGraph` type as its attribute.
3. `MultGraph` is a trait and is the exact generalization of `BaseGraph` trait for graphs having multiple edge types. For now I need this trait because `BaseGraph` is too strict in its signature and so it doesn't deal with multiple type of edges. In a future version, we could also merge these two traits, but for now they are divided for order reasons.
